server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-social.network-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: skillbox
    password: skillbox
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: skillbox
    open-in-view: false

logging:
  level:
    org:
#      springframework: DEBUG

