server:
  port: 8080

spring:
  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-social.network-changelog.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: social.network
    password: social.network
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: social.network
    open-in-view: false
